### ISSUE TITLE
Support alternative Mime-types other than application/json

### ISSUE THREAD

**Issue by medcelerate** [airtasker/spot#1137]
**Is your feature request related to a problem? Please describe.**
Currently all endpoints default to application/json without the ability to change the expected return type. The workaround we have currently is by including the Content-Type response header but it would be better to define a different produces call.

**Describe the solution you'd like**
We would like to be able to pass into a response object a field similar to {@content contentType: "application/octect-strean"}

**Describe alternatives you've considered**
We would also accept a way to do this with jsDoc but the first option would be better.

**Comment by lfportal** [comment]
See https://github.com/airtasker/spot/issues/1150 for a similar issue
