### ISSUE TITLE
Implement the OASv3 schema properties for types

### ISSUE THREAD

**Issue by Thodin3** [airtasker/spot#1367]
**OASv3 schema properties for types needs to be implemented**

The OASv3 has some properties for types that is not implemented currently in Spot :
minLength, maxLength, pattern, minimum, maximum, default, ...

```javascript
        {
          description: "property-schemaprop description for string",
          name: "status",
          in: "header",
          required: true,
          schema: {
            type: "string",
            minLength: 12,
            maxLength: 20,
            pattern: "^[0-9]{3}-[0-9]{8}$"
          }
        },
        {
          description: "property-schemaprop description for integer",
          name: "size",
          in: "header",
          required: true,
          schema: {
            format: "int32",
            type: "integer",
            minimum: 1,
            maximum: 100,
            default: 42
          }
        }
```

**Solution**

Create a new annotation in the description of attributes like it's implemented with **@example** 

**@schemaprop** could be the name, then put the key on the first line and the value on the second line

```ts
/** property-schemaprop description
   * @schemaprop pattern
   * "property-schemaprop-value"
   *  */
  "property-with-schemaprop": string;
  /** property-two-schemaprops description
   * @schemaprop minimum
   * 123
   * @schemaprop default
   * 456
   * */
  "property-with-schemaprops": Integer;
```

Some checks should be done to be compliant with OASv3

**OASv3 schema properties are already there waiting for implementation**

lib/src/generators/openapi3/openapi3-specification.ts
```ts
interface NumberSchemaObjectBase {
  maximum?: number;
  exclusiveMaximum?: boolean;
  minimum?: number;
  exclusiveMinimum?: boolean;
  multipleOf?: number;
  enum?: (number | null)[];
  default?: number;
}

export interface StringSchemaObject extends SchemaObjectBase {
  type: "string";
  maxLength?: number;
  minLength?: number;
  /**
   * OpenAPI allows custom formats. We constrain the format here to those
   * that OpenAPI has defined and custom formats that Spot may produce.
   */
  format?: "date" | "date-time" | "password" | "byte" | "binary";
  pattern?: string;
  enum?: (string | null)[];
  default?: string;
}
```

**Comment by Thodin3** [comment]
Finally, I did it

**Comment by Thodin3** [comment]
Hello @lfportal,
It's a good idea to rename it `@oaSchemaProp` and make `@default` tag works in schema properties as well.
It will be like :
```TypeScript
/** property-schemaprop description
   * @oaSchemaProp pattern
   * "property-schemaprop-value"
   *  */
  "property-with-schemaprop": string;
  /** property-two-schemaprops description
   * @oaSchemaProp minimum
   * 123
   * @default 456
   * */
  "property-with-schemaprops": Integer;
```

Do you agree?

**Comment by Thodin3** [comment]
Hello @lfportal,
Thanks.
I can see that the CI-Test is failing on master now.
This is because of the new feature: property.with.dots

Possible fix is:
add `schemaProps: undefined` in type: `{kind: TypeKind.STRING}` in `lib/src/parsers/query-params-parser.spec.ts:128`

**Comment by lfportal** [comment]
> Hello @lfportal,
> Thanks.
> I can see that the CI-Test is failing on master now.
> This is because of the new feature: property.with.dots
> 
> Possible fix is:
> add `schemaProps: undefined` in type: `{kind: TypeKind.STRING}` in `lib/src/parsers/query-params-parser.spec.ts:128`

Thanks, I'll fix this up

**Comment by lfportal** [comment]
@Thodin3 I'll cut release tomorrow. Thanks for your work on this!

**Comment by Thodin3** [comment]
It was cool ;)

**Comment by amoghsharma1996** [comment]
Question on this one--

Apologies for commenting on a closed issue but these features haven't made it to the official docs yet so I have lots of questions!

An example code block like this:

```
  /** Status
   * @oaSchemaProp default
   * "Active"
   */
  // prettier-ignore
  status: "Active" | "Inactive"
```
When generating the contract, this throws an error like:

`Error: property must be compliant with union type or property not allowed`

Is this not a valid piece of documentation? This works if status is of type String but the whole point is to have Status limited to certain specific string values and to tell the user what it defaults to. The example prop does not throw an error in this same case but there is definitely a difference between example and default in terms of messaging to the user. Any thoughts?

**Comment by Thodin3** [comment]
Hello @amoghsharma1996,

Yes you need to define an enum of string values and set a default value.
It's seems to be a bug. Normally this is same check rules for both example and default.
Could you try `@default` instead of `@oaSchemaProp default` ?
Look at previous comment, `@default` is on one line.
