### ISSUE TITLE
Documentation for how to use non-required/optional body parameters

### ISSUE THREAD

**Issue by hjcoda** [airtasker/spot#1404]
Currently all body parameters are required by default, but how can one specify that certain ones are optional? Please explain.

**Comment by lfportal** [comment]
Hi @emotionalamoeba, I've added a section for optionality here https://github.com/airtasker/spot/wiki/Spot-Syntax#optionality

**Comment by hjcoda** [comment]
Thanks, I've just tried that and it works. Sorry for not realising sooner how to do this :)
