### ISSUE TITLE
@oaSchemaProp example fails with numerical strings

### ISSUE THREAD

**Issue by mneumann** [airtasker/spot#1417]
**Describe the bug**

When using `@oaSchemaProp example`, providing a numerical string like `"123.3"` for a `String` type fails:

```javascript
 /**
   * @oaSchemaProp example
   * "123.3"
   */
  amount: String;
```

```
Error: property type is wrong or property not allowed
    at Object.extractJSDocSchemaProps (.../api-spec/node_modules/@airtasker/spot/build/lib/src/parsers/schemaprop-parser.js:116:31)
```

As `"123.3"` *is* a String, this should work.

**Comment by Thodin3** [comment]
There is also some other linked issues :
When using `@oaSchemaProp default` for `Date` or `DateTime` type it fails:
```ts
/** property-schemaprop date
   * @oaSchemaProp example
   * "1990-12-31"
   *  */
  "property-with-date": Date;
```

When using `@oaSchemaProp example` for Object or Array type it fails:
```ts
/** property-schemaprop array of integer
   * @oaSchemaProp example
   * [1990,12,31]
   *  */
  "property-with-array": Integer[];
```

When using `@oaSchemaProp example` for Union or Intersection type it fails:
```ts
/** property-schemaprop union of string
* @oaSchemaProp example
* "WAITING"
*  */
code?: "VALID" | "NOT_VALID" | "WAITING" | "APPROVED";
```

**Comment by amoghsharma1996** [comment]
Examples seem to work fine now, but the default oaSchemaProp seems busted for enum strings.

For example

```
  /** Status
   * @oaSchemaProp default
   * "Active"
   */
  // prettier-ignore
  status: "Active" | "Closed"
```

Throws an error

**Comment by Thodin3** [comment]
Hello @amoghsharma1996,

It's seems to be a bug.
Normally this is same check rules for both example and default.
Could you try `@default` instead of `@oaSchemaProp default`?
`@default` is on one line.

**Comment by amoghsharma1996** [comment]
Hey @Thodin3 same issue trying default.

Whether I try it on 1 line versus 2 lines:

`@default "Active"`
or
```
@default
"Active"
```

In either scenario I still receive the same error, 
`Error: property must be compliant with union type or property not allowed`

I have opened up an issue to track this #1761
