### ISSUE TITLE
Add support for HEAD methods

### ISSUE THREAD

**Issue by recardon** [airtasker/spot#1461]
Currently Spot does not support generating OAS contracts in which HEAD methods are defined.

**Comment by recardon** [comment]
Started working on it.

**Comment by recardon** [comment]
Finished working on it, waiting for your review. Cheers!

**Comment by recardon** [comment]
Hello @lfportal, it would be very cool it you would create a new release including this issue. THanks in advance!

**Comment by lfportal** [comment]
Hey @recardon, I've cut a new release [v1.9.0](https://github.com/airtasker/spot/releases/tag/v1.9.0) including this commit.

**Comment by recardon** [comment]
Thanks, good evening!
