### ISSUE TITLE
OpenAPI object access in memory

### ISSUE THREAD

**Issue by stuft2** [airtasker/spot#455]
Is there a way to generate the document in memory? I'd like to use my OAS document to drive the services/tools I'm building. It would be really cool if I could export an OpenAPI document from a typescript file and import it to use programmatically. For example:

```ts
/* api.ts */
import {api, endpoint, request, response, body} from '@airtasker/spot'

@api({
    name: "My API"
})
export default class Api {}

@endpoint({
    method: "POST",
    path: "/users"
})
class CreateUser {
    @request
    request(@body body: CreateUserRequest) {}

    @response({ status: 201 })
    response(@body body: CreateUserResponse) {}
}

interface CreateUserRequest {
    firstName: string;
    lastName: string;
}

interface CreateUserResponse {
    firstName: string;
    lastName: string;
    role: string;
}
```

```ts
/* some-file.ts */
import Api from './api.ts'

/* Access OpenAPI document as JSON here */
console.log(Api.openapi) // expected output: 3.0.0
```

**Comment by alephao** [comment]
Currently, I don't think this is possible since we only expose the spot syntax/decorators, and we don't expose the parsers and generators.

I like the idea of exposing the generators and parsers, then you could leverage the spot infrastructure to power your tool e.g.:

```ts
import { parser, generateOpenApiV3, openApiV3 } from "@airtasker/spot/generators"

const parsed = parser('./api.ts');
const contractDefinition = generateOpenApiV3(parsed, "json");
const contract = openApiV3(contractDefinition);

console.log(contract.openapi) // 3.0.0
```

Any thoughts @fwouts @lfportal?

**Comment by lfportal** [comment]
I think this is a great idea.

**Comment by fwouts** [comment]
+1 would love to see this.

**Comment by kbanman** [comment]
this would also allow for extensibility. I'd love to inject some AWS-specific metadata before generating the output.
