### ISSUE TITLE
Switch Speccy to Spectral

### ISSUE THREAD

**Issue by philsturgeon** [airtasker/spot#629]
Hey I'm the original author of Speccy. I'm doing the rounds letting people know they should switch to [Spectral](https://stoplight.io/spectral/). Speccy is not getting much love these days, and Spectral is like its considerably more mature and advanced replacement. 

You can use the TypeScript API directly instead of running things through the CLI too if you like. Seems like it might be up your alley.

**Comment by lfportal** [comment]
Hey @philsturgeon, thanks for the heads up!
